import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { extractBill, pdfFallbackMessage } from "../lib/ocr";
import { extractPdfText } from "../lib/pdf_extract";

const FIX_DIR = path.resolve(__dirname, "fixtures/bills");

// Take 5 representative NL PDFs for the v9 sprint criterion ("4/5 PDF
// fixtures werken"). These are all text-based PDFs generated by
// scripts/generate-ocr-fixtures.ts.
const PDF_NAMES = ["nl-tel-kpn", "nl-tel-vodafone", "nl-ene-eneco", "nl-verz-centraal", "nl-bank-ing"];

describe("PDF fixtures: text extraction + flow", () => {
  for (const name of PDF_NAMES) {
    it(`${name}: pdfjs extracts non-empty text`, async () => {
      const buf = fs.readFileSync(path.join(FIX_DIR, `${name}.pdf`));
      const r = await extractPdfText(buf);
      expect(r.ok).toBe(true);
      expect(r.empty).toBe(false);
      expect(r.text.length).toBeGreaterThan(40);
    });
  }

  it("extractBill never throws for PDF fixtures (graceful fallback)", async () => {
    for (const name of PDF_NAMES) {
      const buf = fs.readFileSync(path.join(FIX_DIR, `${name}.pdf`));
      const r = await extractBill(buf, "application/pdf");
      expect(r.imageHash).toMatch(/^[a-f0-9]{64}$/);
      // Either succeeded (live LLM) or returned a PDF marker
      if (!r.ok) {
        expect(r.rawText).toMatch(/PDF_/);
        expect(r.needsManual).toBe(true);
      }
    }
  });

  it("garbage 'PDF' triggers EXTRACT_FAIL marker, not a crash", async () => {
    const r = await extractBill(Buffer.from("%PDF-garbage"), "application/pdf");
    expect(r.ok).toBe(false);
    expect(r.rawText).toMatch(/PDF_(EXTRACT_FAIL|SCAN_NO_TEXT|OCR_SKIPPED|LLM_ERR)/);
  });
});

describe("pdfFallbackMessage: user-facing strings", () => {
  it("returns null on non-PDF rawText", () => {
    expect(pdfFallbackMessage("")).toBeNull();
    expect(pdfFallbackMessage("OCR_SKIPPED_NO_API_KEY")).toBeNull();
    expect(pdfFallbackMessage("just some OCR text")).toBeNull();
  });

  it("returns NL message for SCAN_NO_TEXT (image-in-pdf)", () => {
    const m = pdfFallbackMessage("PDF_SCAN_NO_TEXT");
    expect(m).toMatch(/ingescande/);
    expect(m).toMatch(/foto/);
  });

  it("returns NL message for EXTRACT_FAIL", () => {
    expect(pdfFallbackMessage("PDF_EXTRACT_FAIL: invalid PDF")).toMatch(/uitlezen/);
  });

  it("returns NL message for LLM_ERR", () => {
    expect(pdfFallbackMessage("PDF_LLM_ERR: 429")).toMatch(/AI-service/);
  });

  it("returns NL message for PARSE_LOW_CONFIDENCE", () => {
    expect(pdfFallbackMessage("PDF_PARSE_LOW_CONFIDENCE")).toMatch(/handmatig/);
  });

  it("returns NL message for OCR_SKIPPED_NO_API_KEY (PDF variant)", () => {
    expect(pdfFallbackMessage("PDF_OCR_SKIPPED_NO_API_KEY")).toMatch(/uitgeschakeld/);
  });
});
